[package]
name = "adb-btree"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crc32fast.workspace = true
adb-core = { path = "../adb-core" }
adb-page = { path = "../adb-page" }
adb-buffer = { path = "../adb-buffer" }
parking_lot.workspace = true
thiserror.workspace = true
serde.workspace = true
bincode.workspace = true

[dev-dependencies]
tempfile.workspace = true
