[package]
name = "adb-demo-1-5-2"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
adb-core = { path = "../../crates/adb-core" }
adb-page = { path = "../../crates/adb-page" }
adb-btree = { path = "../../crates/adb-btree" }
adb-storage = { path = "../../crates/adb-storage" }
adb-engine = { path = "../../crates/adb-engine" }
tempfile.workspace = true
